name: Stable Deploym

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: EXTRACT NPM VERSION
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      -
        name: SETUP QEMUX
        uses: docker/setup-qemu-action@v1
      -
        name: SET UP DOCKERX
        uses: docker/setup-buildx-action@v1
      -
        name: LOGIN TO DOCKERHUB
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build Docker and Push to BOILERPLATE
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile
          tags: |
            shellcodesniper/boilerplate:rollback
          cache-from: type=local,src=/tmp/.buildx-cache-boilerplateback
          cache-to: type=local,dest=/tmp/.buildx-cache-new-boilerplateback,mode=max
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-boilerplateback
          mv /tmp/.buildx-cache-new-boilerplateback /tmp/.buildx-cache-boilerplateback
